import { defineEventHandler } from 'h3'

export default defineEventHandler(() => {
  let english = "Meet Nicolas Leboucher, an ambitious Software Developer and IoT Engineer currently excelling in his Master's program at ESILV, a leading Engineering School in France. Passionate about innovation, Nicolas has a knack for creating cutting-edge solutions in the realms of software engineering and artificial intelligence. \n With a strong background in diverse programming languages, including Python, C#, and C++, he has proven his prowess in developing various applications and systems, ranging from IoT devices to complex databases. \n Having garnered significant experience through internships at esteemed organizations like Schneider Electric and Vizzia, Nicolas has demonstrated his proficiency in handling complex projects, including the development of AI-driven waste surveillance cameras and the creation of a C# WPF application for test automation. \n As an avid researcher at the DVIC Innovation Center, Nicolas is currently involved in spearheading groundbreaking projects that leverage technologies such as ROS, LSTM, and neural networks for drone control and natural language processing. His leadership skills shine through his role as the project manager for the Rover Heliport, where he led a team in the creation of an automated geolocation-enabled drone system, showcasing his expertise in electronics, PCB design, and soldering. \n Beyond his academic and professional pursuits, Nicolas actively engages in community service, serving as a mentor for school students and contributing his time to the Red Cross. With his extensive skill set, unwavering dedication, and innovative mindset, Nicolas is poised to make significant contributions to the ever-evolving landscape of technology and engineering."
  let francais = "Rencontrez Nicolas Leboucher, un développeur de logiciels ambitieux et ingénieur IoT, actuellement en train d'exceller dans son programme de Master à l'ESILV, une école d'ingénierie de premier plan en France. Passionné par l'innovation, Nicolas a un don pour créer des solutions de pointe dans les domaines du génie logiciel et de l'intelligence artificielle.\n  Avec une solide formation dans divers langages de programmation, y compris Python, C# et C++, il a prouvé sa compétence dans le développement de diverses applications et systèmes, allant des dispositifs IoT aux bases de données complexes. \n Ayant acquis une expérience significative grâce à des stages dans des organisations estimées telles que Schneider Electric et Vizzia, Nicolas a démontré sa maîtrise dans la gestion de projets complexes, y compris le développement de caméras de surveillance des déchets pilotées par l'IA et la création d'une application WPF C# pour l'automatisation des tests.\n  En tant que chercheur passionné au Centre d'Innovation DVIC, Nicolas est actuellement impliqué dans la direction de projets révolutionnaires qui tirent parti de technologies telles que ROS, LSTM et les réseaux neuronaux pour le contrôle de drones et le traitement du langage naturel. Ses compétences en leadership ressortent dans son rôle de chef de projet pour le Rover Heliport, où il a dirigé une équipe dans la création d'un système de drone automatisé avec géolocalisation, démontrant son expertise en électronique, conception de PCB et soudage. \n Au-delà de ses poursuites académiques et professionnelles, Nicolas s'engage activement dans le service communautaire, servant de mentor pour les élèves des écoles et consacrant son temps à la Croix-Rouge. Avec son ensemble de compétences étendu, son dévouement inébranlable et son esprit innovant, Nicolas est prêt à apporter des contributions significatives au paysage en constante évolution de la technologie et de l'ingénierie."



  return [
    {
      id: 1,
      description: {
        en: english.innerHTML.split('\n').join('<br>'),
     id_ID: francais.split('\n').join('<br>'),
      },
    },
  ]
})
